

template header

ruleName
salience
duration
condition
consequence
enabled
dateEffective
cronExpression
dateExpires
package io.je.runtime;

import java.time.LocalDateTime;
import java.time.Instant;

import io.je.utilities.beans.JEMessage;
import io.je.utilities.beans.JEBlockMessage;
import java.util.Date;
import java.util.HashMap;
import jeclasses.*;
import io.je.utilities.log.JELogger;
import io.je.utilities.execution.Executioner;
import io.je.utilities.beans.JEEvent;
import io.je.utilities.beans.JEVariable;
import utils.maths.*;
import io.je.ruleengine.utils.JEMathUtils;
import io.je.project.variables.VariableManager;

template "JobEngineRuleTemplate"

rule "@{ruleName}"  @Propagation(IMMEDIATE)
dialect "java" 
salience @{salience}
duration (@{duration})
enabled @{enabled}
date-effective @{dateEffective}
date-expires @{dateExpires}
timer (cron:@{cronExpression})

when
   @{condition}
then
   @{consequence}
   
    
end


end template