package io.je.runtime;
import java.time.LocalDateTime;
import io.je.utilities.beans.JEMessage;
import io.je.utilities.beans.JEBlockMessage;
import java.util.Date;
import java.util.HashMap;
import classes.*;
import io.je.utilities.logger.JELogger;
import io.je.utilities.execution.Executioner;
import io.je.utilities.beans.JEEvent;
import io.je.utilities.math.*;

rule "_bd4e9df9-72e9-bd90-9264-f3a2ff2b26c8_1111"  @Propagation(IMMEDIATE)
dialect "java" 
salience 0

enabled true


timer (cron:0/4 * * * * ? *)
when

then
   JEMessage message = new JEMessage();
JEBlockMessage blockMsg = new JEBlockMessage("Inform0","111111111");
message.addBlockMessage(blockMsg);
message.setType("BlockMessage");
message.setExecutionTime(LocalDateTime.now().toString());
Executioner.informRuleBlock("123","bd4e9df9-72e9-bd90-9264-f3a2ff2b26c8", message );
end


