

template header

ruleName
salience
duration
condition
consequence
enabled
dateEffective
cronExpression
dateExpires
package io.je.runtime;

import java.util.HashMap;
import classes.*;
import io.je.utilities.logger.JELogger;
import io.je.utilities.execution.Executioner;
import io.je.utilities.beans.JEEvent;
import io.je.utilities.math.*;

template "JobEngineRuleTemplate"

rule "@{ruleName}"  @Propagation(IMMEDIATE)
dialect "java" 
salience @{salience}
duration (@{duration})
enabled @{enabled}
date-effective @{dateEffective}
date-expires @{dateExpires}
timer (cron:@{cronExpression})

when
   @{condition}
then
   @{consequence}
   
    
end


end template